payload:
  # NAME: Meta
  # DESCRIPTION: WhatsApp / Facebook / Instagram / Meta 分流规则
  # UPDATED: 2026-05-11
  # ================================
  # 规则统计
  # ================================
  # HOST: 0
  # HOST-SUFFIX: 33
  # HOST-KEYWORD: 4
  # USER-AGENT: 0
  # IP-CIDR: 0
  # IP6-CIDR: 0
  # IP-ASN: 1
  # TOTAL: 38
  #
  # ================================
  # 规则内容
  # ================================
  # WhatsApp / Facebook / Instagram / Meta
  # ================================
  - DOMAIN-SUFFIX,aboutfacebook.com
  - DOMAIN-SUFFIX,accountkit.com
  - DOMAIN-SUFFIX,facebook.com
  - DOMAIN-SUFFIX,facebook.net
  - DOMAIN-SUFFIX,facebookmail.com
  - DOMAIN-SUFFIX,facebookmessenger.com
  - DOMAIN-SUFFIX,fb.com
  - DOMAIN-SUFFIX,fb.me
  - DOMAIN-SUFFIX,fbcdn.com
  - DOMAIN-SUFFIX,fbcdn.net
  - DOMAIN-SUFFIX,fbmessenger.com
  - DOMAIN-SUFFIX,fbsbx.com
  - DOMAIN-SUFFIX,fbsbx.net
  - DOMAIN-SUFFIX,fburl.com
  - DOMAIN-SUFFIX,instagram.com
  - DOMAIN-SUFFIX,instagram.net
  - DOMAIN-SUFFIX,cdninstagram.com
  - DOMAIN-SUFFIX,ig.me
  - DOMAIN-SUFFIX,igcdn.com
  - DOMAIN-SUFFIX,threads.net
  - DOMAIN-SUFFIX,m.me
  - DOMAIN-SUFFIX,msngr.com
  - DOMAIN-SUFFIX,oculus.com
  - DOMAIN-SUFFIX,oculuscdn.com
  - DOMAIN-SUFFIX,meta.com
  - DOMAIN-SUFFIX,meta.org
  - DOMAIN-SUFFIX,whatsapp.com
  - DOMAIN-SUFFIX,whatsapp.net
  - DOMAIN-SUFFIX,wa.me
  - DOMAIN-SUFFIX,web.whatsapp.com
  - DOMAIN-SUFFIX,mmg.whatsapp.net
  - DOMAIN-SUFFIX,graph.facebook.com
  - DOMAIN-SUFFIX,graph.instagram.com
  - DOMAIN-KEYWORD,facebook
  - DOMAIN-KEYWORD,instagram
  - DOMAIN-KEYWORD,whatsapp
  - DOMAIN-KEYWORD,fbcdn
  - IP-ASN,32934
